### PR TITLE
Fix issue with ANSI escape characters.

### LINKED ISSUE #3: Reveals characters with ANSI escape sequences
When using the `read` module in silent mode with an ANSI formatted prompt and setting a *replace* character upon the backspace keypress event the *replace* character is no longer respected, ie, the plain text is displayed on screen.

Without ANSI escape sequences this issue is not present.

I tracked this down to the `write` method and have implemented a fix, within the ANSI conditional clause (https://github.com/isaacs/mute-stream/blob/master/mute.js#L103) I added:

```
if(c.indexOf(this._prompt) === 0) {
  var text = c.replace(this._prompt, '');
  text = text.replace(/./g, this.replace);
  c = this._prompt + text;
}
```

I am using a modified version of the `read` module which allows passing the unformatted prompt length when calling `ReadlineInterface.setPrompt()` (https://github.com/joyent/node/issues/3860).

```
node --version => v0.10.29
```

The patched version of `mute-stream` is here:

https://github.com/freeformsystems/cli-input/blob/master/lib/mute.js

Interested in a pull request?

### PR DESCRIPTION
**Pull request by tmpfs**
Closes #3.

### CODE REVIEW

**Comment by gangstead** [comment]
Fixed in https://github.com/npm/mute-stream/commit/dc7a0ea89d7c482827cc9fe3805651b0217662c7  I think this one can be closed.

**Comment by tmpfs** [comment]
Closed as manually merged.

**Comment by tmpfs** [comment]
Can you publish v0.0.7 so I can use it please? At the moment I only see v0.0.6 in the registry (https://www.npmjs.com/package/mute-stream). Thanks.

**Comment by isaacs** [comment]
Ah, well that's odd.  Must've missed it, or maybe had limited internet when I landed this patch.

Anyway, published now, sorry for the delay.

**Pull request closed without merging**
